### ISSUE TITLE
More info on making requests in README

### ISSUE THREAD

**Issue by mrcoles** [VeliovGroup/instagram-node#1]
To make requests would I need to use something like `Meteor.bindEnvironment` in callbacks or anything like? It’s been a while since I’ve looked at the requirements of working with an NPM package in Meteor that makes I/O calls.

It’d be great to see a simple example of a working call in the README.

**Comment by dr-dimitru** [comment]
Hello @mrcoles  ,

Sorry for answering almost after a 3 years later.
Somehow I've missed it.

Yes, all non-meteor callbacks (*as with NPM package in this case*) should be wrapped into `bindEnvironment`.

Feel free to reopen it in case if the issue is still persists on your end.
